# Generated by Django 6.0.1 on 2026-02-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaalmoco',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='diaalmoco',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.AddField(
            model_name='diaalmoco',
            name='id_dia_almoco',
            field=models.AutoField(db_column='id_dia_almoco', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_pessoa',
            field=models.AutoField(db_column='id_pessoa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diaalmoco',
            name='dia',
            field=models.DateField(db_column='dia'),
        ),
        migrations.AlterField(
            model_name='diaalmoco',
            name='pessoa',
            field=models.ForeignKey(db_column='pessoa_id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='app_almoco.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(db_column='nome_completo', max_length=45),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(db_column='telefone', max_length=45),
        ),
        migrations.AlterModelTable(
            name='diaalmoco',
            table='dia_almoco',
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='pessoa',
        ),
    ]
